### ISSUE TITLE
当使用 illyria client with zookeeper，zookeeper 服务器未成功连接时，没有报错

### ISSUE THREAD

**Issue by adoyle-h** [XadillaX/illyria2#1]
![image](https://cloud.githubusercontent.com/assets/1998490/10363100/05b97456-6de5-11e5-81e8-71ea0ff81b4c.png)

在这里只监听了 connected 事件，如果它一直没连上 zookeeper 怎么办？

![image](https://cloud.githubusercontent.com/assets/1998490/10363122/35cbc716-6de5-11e5-900b-24187b403c26.png)

我加了监听 expired 和  disconnected 事件，仍然没有任何输出。

我想要确保当未能成功连接上 zookeeper，就反馈一个错误。

**Comment by XadillaX** [comment]
求实现 `timeout`，详参照 https://github.com/XadillaX/illyria2/blob/53b3e4e3822d15def65834d56faf5716192f512a/lib/client.js#L226
